#%RAML 0.8
title: Client Oracle Primavera API
version: v1
baseUri: http://localhost:8997/clientprimavera-{version}

mediaType: application/json

protocols: [ HTTP, HTTPS ]

traits: !include ./traits.raml   

documentation: 
  - title: Getting Started 
    content: Welcome to this Client Primavera API
  - title: Authentication 
    content: How to authenticate in this API
    
    
/firstresource: 
  displayName: First Resource
  description: This is the first resource of this client API. 
  is: [secured]
  get:
    queryParameters: 
      field: 
        displayName: Field to filtering data 
        description: Search Field 
        required: false
        type: string
        minLength: 2 
        example: date-created
      page: 
        displayName: Paging
        description: Number of records to retrieve data
        required: false 
        type: integer
        minimum: 0 
        maximum: 10 
        example: 5
    responses: 
      200: 
        description: Response accepted
        body: 
          application/json: 
            example: !include ./responses/200.example
      400: 
        description: Failed resource 
        body: 
          application/json: 
            example: !include ./responses/400.example
      401: 
        description: Failed resource by headers
        body: 
          application/json: 
            example: !include ./responses/401.example
      404: 
        description: Not Found Resource 
        body: 
          application/json: 
            example: !include ./responses/404.example
      409: 
        description: Failed resource by field 
        body: 
          application/json: 
            example: !include ./responses/409.example
      500: 
        description: Not able to reach this resource 
        body: 
          application/json: 
            example: !include ./responses/500.example
   
    
      