- secured: 
    headers: 
      Authorization: 
        description: This header is used to authenticate a proper user before to reach a resource. UUID Version 4
        displayName: Authorization
        type: string
        required: true
        default: "e01653af-be22-47e1-b582-54d7c0c37d36"
        pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ 
        example: "64adaed0-23a0-4124-8e7d-06aba5a7e0fc"